import './globals.css';
import { Inter } from 'next/font/google';
import AppHeader from '@/components/AppHeader';
import AppFooter from '@/components/AppFooter';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader />
        <div className="xl:container my-0 mx-auto px-5">{children}</div>
        <AppFooter />
      </body>
    </html>
  );
}
